// [อังกฤษ, ไทย, ตัวอย่างประโยค, หมวด]
const WORDS = [
  ["hello","สวัสดี","Hello, how are you?","ทักทาย"],
  ["goodbye","ลาก่อน","Goodbye, see you tomorrow.","ทักทาย"],
  ["thank you","ขอบคุณ","Thank you for your help.","ทักทาย"],
  ["please","กรุณา / ได้โปรด","Please sit down.","ทักทาย"],
  ["sorry","ขอโทษ","I'm sorry I'm late.","ทักทาย"],
  ["welcome","ยินดีต้อนรับ","Welcome to Thailand.","ทักทาย"],
  ["apple","แอปเปิล","I eat an apple every day.","อาหาร"],
  ["banana","กล้วย","Monkeys love bananas.","อาหาร"],
  ["rice","ข้าว","We eat rice for lunch.","อาหาร"],
  ["water","น้ำ","Can I have some water?","อาหาร"],
  ["bread","ขนมปัง","She bought fresh bread.","อาหาร"],
  ["chicken","ไก่","Fried chicken is delicious.","อาหาร"],
  ["egg","ไข่","I had two eggs for breakfast.","อาหาร"],
  ["milk","นม","He drinks milk every morning.","อาหาร"],
  ["dog","สุนัข","The dog is barking.","สัตว์"],
  ["cat","แมว","The cat sleeps on the sofa.","สัตว์"],
  ["bird","นก","A bird is singing.","สัตว์"],
  ["fish","ปลา","There are fish in the pond.","สัตว์"],
  ["elephant","ช้าง","The elephant is the symbol of Thailand.","สัตว์"],
  ["horse","ม้า","She rides a horse.","สัตว์"],
  ["red","สีแดง","The rose is red.","สี"],
  ["blue","สีน้ำเงิน / สีฟ้า","The sky is blue.","สี"],
  ["green","สีเขียว","The grass is green.","สี"],
  ["yellow","สีเหลือง","The sun is yellow.","สี"],
  ["black","สีดำ","He wears a black hat.","สี"],
  ["white","สีขาว","Snow is white.","สี"],
  ["one","หนึ่ง","I have one brother.","ตัวเลข"],
  ["two","สอง","Two plus two is four.","ตัวเลข"],
  ["three","สาม","There are three books.","ตัวเลข"],
  ["ten","สิบ","Count to ten.","ตัวเลข"],
  ["hundred","ร้อย","A hundred people came.","ตัวเลข"],
  ["family","ครอบครัว","I love my family.","ครอบครัว"],
  ["mother","แม่","My mother is a teacher.","ครอบครัว"],
  ["father","พ่อ","My father works at a bank.","ครอบครัว"],
  ["brother","พี่ชาย / น้องชาย","My brother plays football.","ครอบครัว"],
  ["sister","พี่สาว / น้องสาว","My sister likes music.","ครอบครัว"],
  ["friend","เพื่อน","She is my best friend.","ครอบครัว"],
  ["school","โรงเรียน","The children go to school.","ทั่วไป"],
  ["book","หนังสือ","This book is interesting.","ทั่วไป"],
  ["house","บ้าน","They built a new house.","ทั่วไป"],
  ["car","รถยนต์","He drives a red car.","ทั่วไป"],
  ["time","เวลา","What time is it?","ทั่วไป"],
  ["happy","มีความสุข","I am happy today.","ทั่วไป"],
  ["beautiful","สวยงาม","What a beautiful view!","ทั่วไป"],
  ["difficult","ยาก","This question is difficult.","ทั่วไป"],
  ["learn","เรียนรู้","I want to learn English.","ทั่วไป"],
  ["understand","เข้าใจ","Do you understand me?","ทั่วไป"],
  ["travel","เดินทาง","They love to travel.","ทั่วไป"],
  ["airport","สนามบิน","We arrived at the airport.","เดินทาง"],
  ["hotel","โรงแรม","The hotel is near the beach.","เดินทาง"],
  ["ticket","ตั๋ว","I need to buy a ticket.","เดินทาง"],
  ["where","ที่ไหน","Where is the toilet?","เดินทาง"],
  ["how much","เท่าไหร่","How much is this?","เดินทาง"]
];
