// [อังกฤษ, ไทย, ตัวอย่างประโยค, หมวด]
const WORDS = [
  ["hello","สวัสดี","Hello, how are you?","ทักทาย"],
  ["goodbye","ลาก่อน","Goodbye, see you tomorrow.","ทักทาย"],
  ["thank you","ขอบคุณ","Thank you for your help.","ทักทาย"],
  ["please","กรุณา / ได้โปรด","Please sit down.","ทักทาย"],
  ["sorry","ขอโทษ","I'm sorry I'm late.","ทักทาย"],
  ["welcome","ยินดีต้อนรับ","Welcome to Thailand.","ทักทาย"],
  ["apple","แอปเปิล","I eat an apple every day.","อาหาร"],
  ["banana","กล้วย","Monkeys love bananas.","อาหาร"],
  ["rice","ข้าว","We eat rice for lunch.","อาหาร"],
  ["water","น้ำ","Can I have some water?","อาหาร"],
  ["bread","ขนมปัง","She bought fresh bread.","อาหาร"],
  ["chicken","ไก่","Fried chicken is delicious.","อาหาร"],
  ["egg","ไข่","I had two eggs for breakfast.","อาหาร"],
  ["milk","นม","He drinks milk every morning.","อาหาร"],
  ["dog","สุนัข","The dog is barking.","สัตว์"],
  ["cat","แมว","The cat sleeps on the sofa.","สัตว์"],
  ["bird","นก","A bird is singing.","สัตว์"],
  ["fish","ปลา","There are fish in the pond.","สัตว์"],
  ["elephant","ช้าง","The elephant is the symbol of Thailand.","สัตว์"],
  ["horse","ม้า","She rides a horse.","สัตว์"],
  ["red","สีแดง","The rose is red.","สี"],
  ["blue","สีน้ำเงิน / สีฟ้า","The sky is blue.","สี"],
  ["green","สีเขียว","The grass is green.","สี"],
  ["yellow","สีเหลือง","The sun is yellow.","สี"],
  ["black","สีดำ","He wears a black hat.","สี"],
  ["white","สีขาว","Snow is white.","สี"],
  ["one","หนึ่ง","I have one brother.","ตัวเลข"],
  ["two","สอง","Two plus two is four.","ตัวเลข"],
  ["three","สาม","There are three books.","ตัวเลข"],
  ["ten","สิบ","Count to ten.","ตัวเลข"],
  ["hundred","ร้อย","A hundred people came.","ตัวเลข"],
  ["family","ครอบครัว","I love my family.","ครอบครัว"],
  ["mother","แม่","My mother is a teacher.","ครอบครัว"],
  ["father","พ่อ","My father works at a bank.","ครอบครัว"],
  ["brother","พี่ชาย / น้องชาย","My brother plays football.","ครอบครัว"],
  ["sister","พี่สาว / น้องสาว","My sister likes music.","ครอบครัว"],
  ["friend","เพื่อน","She is my best friend.","ครอบครัว"],
  ["school","โรงเรียน","The children go to school.","ทั่วไป"],
  ["book","หนังสือ","This book is interesting.","ทั่วไป"],
  ["house","บ้าน","They built a new house.","ทั่วไป"],
  ["car","รถยนต์","He drives a red car.","ทั่วไป"],
  ["time","เวลา","What time is it?","ทั่วไป"],
  ["happy","มีความสุข","I am happy today.","ทั่วไป"],
  ["beautiful","สวยงาม","What a beautiful view!","ทั่วไป"],
  ["difficult","ยาก","This question is difficult.","ทั่วไป"],
  ["learn","เรียนรู้","I want to learn English.","ทั่วไป"],
  ["understand","เข้าใจ","Do you understand me?","ทั่วไป"],
  ["travel","เดินทาง","They love to travel.","ทั่วไป"],
  ["airport","สนามบิน","We arrived at the airport.","เดินทาง"],
  ["hotel","โรงแรม","The hotel is near the beach.","เดินทาง"],
  ["ticket","ตั๋ว","I need to buy a ticket.","เดินทาง"],
  ["where","ที่ไหน","Where is the toilet?","เดินทาง"],
  ["how much","เท่าไหร่","How much is this?","เดินทาง"]
,
  ["agenda","วาระการประชุม","Please review the agenda before the meeting.","TOEIC"],
  ["attend","เข้าร่วม","All employees must attend the training.","TOEIC"],
  ["schedule","กำหนดการ / จัดตารางเวลา","Let's schedule a meeting for Monday.","TOEIC"],
  ["deadline","กำหนดส่ง","The deadline for the report is Friday.","TOEIC"],
  ["postpone","เลื่อนออกไป","The launch was postponed until May.","TOEIC"],
  ["cancel","ยกเลิก","They had to cancel the conference.","TOEIC"],
  ["colleague","เพื่อนร่วมงาน","I discussed the plan with a colleague.","TOEIC"],
  ["supervisor","หัวหน้างาน","Please report to your supervisor.","TOEIC"],
  ["employer","นายจ้าง","The employer offers health insurance.","TOEIC"],
  ["employee","พนักงาน","Each employee received a bonus.","TOEIC"],
  ["candidate","ผู้สมัคร","The candidate has five years of experience.","TOEIC"],
  ["resume","ประวัติย่อ (เรซูเม่)","Please attach your resume to the application.","TOEIC"],
  ["apply for","สมัคร (งาน)","She applied for a position in marketing.","TOEIC"],
  ["qualification","คุณสมบัติ / วุฒิ","He has the right qualifications for the job.","TOEIC"],
  ["promote","เลื่อนตำแหน่ง / ส่งเสริม","She was promoted to manager.","TOEIC"],
  ["resign","ลาออก","He resigned to start his own company.","TOEIC"],
  ["retire","เกษียณ","My father will retire next year.","TOEIC"],
  ["salary","เงินเดือน","The salary is paid monthly.","TOEIC"],
  ["benefit","สวัสดิการ / ประโยชน์","The company offers excellent benefits.","TOEIC"],
  ["invoice","ใบแจ้งหนี้","Please send the invoice by email.","TOEIC"],
  ["receipt","ใบเสร็จ","Keep the receipt for your records.","TOEIC"],
  ["refund","คืนเงิน","You can get a full refund within 30 days.","TOEIC"],
  ["budget","งบประมาณ","We need to reduce our budget.","TOEIC"],
  ["revenue","รายได้","Annual revenue increased by 10 percent.","TOEIC"],
  ["profit","กำไร","The firm made a large profit this year.","TOEIC"],
  ["expense","ค่าใช้จ่าย","Travel expenses will be reimbursed.","TOEIC"],
  ["estimate","ประเมินราคา / การประเมิน","Can you give me an estimate?","TOEIC"],
  ["payment","การชำระเงิน","Payment is due within 14 days.","TOEIC"],
  ["purchase","ซื้อ / การซื้อ","She made a purchase online.","TOEIC"],
  ["order","สั่งซื้อ / คำสั่งซื้อ","We placed an order for new laptops.","TOEIC"],
  ["shipment","การขนส่งสินค้า","The shipment will arrive on Tuesday.","TOEIC"],
  ["deliver","จัดส่ง","We deliver within three business days.","TOEIC"],
  ["inventory","สินค้าคงคลัง","We check our inventory every week.","TOEIC"],
  ["supplier","ผู้จัดหาสินค้า","The supplier raised its prices.","TOEIC"],
  ["customer","ลูกค้า","The customer is always right.","TOEIC"],
  ["client","ลูกค้า (ผู้ใช้บริการ)","We are meeting a new client today.","TOEIC"],
  ["contract","สัญญา","Both parties signed the contract.","TOEIC"],
  ["negotiate","เจรจาต่อรอง","They negotiated a better price.","TOEIC"],
  ["proposal","ข้อเสนอ","The board approved the proposal.","TOEIC"],
  ["approve","อนุมัติ","The manager approved my vacation request.","TOEIC"],
  ["require","ต้องการ / กำหนดให้","This job requires good communication skills.","TOEIC"],
  ["submit","ส่ง (เอกสาร)","Submit your application by noon.","TOEIC"],
  ["review","ตรวจทาน / รีวิว","Please review the document carefully.","TOEIC"],
  ["revise","แก้ไขปรับปรุง","We revised the schedule.","TOEIC"],
  ["confirm","ยืนยัน","I'd like to confirm my reservation.","TOEIC"],
  ["reserve","จอง","I reserved a table for four.","TOEIC"],
  ["available","ว่าง / มีให้","Is the manager available now?","TOEIC"],
  ["board","คณะกรรมการ / ขึ้น (เครื่องบิน)","The board of directors will meet today.","TOEIC"],
  ["headquarters","สำนักงานใหญ่","Our headquarters is in Bangkok.","TOEIC"],
  ["branch","สาขา","They opened a new branch downtown.","TOEIC"],
  ["department","แผนก","She works in the sales department.","TOEIC"],
  ["facility","สิ่งอำนวยความสะดวก","The hotel has excellent facilities.","TOEIC"],
  ["equipment","อุปกรณ์","The office equipment is old.","TOEIC"],
  ["maintenance","การบำรุงรักษา","The elevator is under maintenance.","TOEIC"],
  ["install","ติดตั้ง","A technician will install the software.","TOEIC"],
  ["replace","เปลี่ยนแทน","Please replace the broken printer.","TOEIC"],
  ["recommend","แนะนำ","I recommend this restaurant.","TOEIC"],
  ["in advance","ล่วงหน้า","Please book tickets in advance.","TOEIC"],
  ["as soon as possible","โดยเร็วที่สุด","Please reply as soon as possible.","TOEIC"],
  ["be responsible for","รับผิดชอบ","She is responsible for the project.","TOEIC"],
  ["be located in","ตั้งอยู่ที่","The office is located in Silom.","TOEIC"],
  ["according to","ตามที่ / อ้างอิงจาก","According to the report, sales are up.","TOEIC"],
  ["regarding","เกี่ยวกับ","I'm writing regarding your order.","TOEIC"],
  ["in charge of","รับผิดชอบดูแล","He is in charge of hiring.","TOEIC"],
  ["boarding pass","บัตรขึ้นเครื่อง","Show your boarding pass at the gate.","TOEIC"],
  ["itinerary","กำหนดการเดินทาง","Here is your travel itinerary.","TOEIC"],
  ["delay","ล่าช้า","The flight was delayed by two hours.","TOEIC"],
  ["luggage","สัมภาระ / กระเป๋าเดินทาง","Your luggage is at carousel 3.","TOEIC"],
  ["artificial intelligence","ปัญญาประดิษฐ์","Artificial intelligence is changing how we work.","AI"],
  ["machine learning","การเรียนรู้ของเครื่อง","Machine learning finds patterns in data.","AI"],
  ["deep learning","การเรียนรู้เชิงลึก","Deep learning uses many layers of neurons.","AI"],
  ["neural network","โครงข่ายประสาทเทียม","A neural network mimics the human brain.","AI"],
  ["algorithm","อัลกอริทึม / ขั้นตอนวิธี","The algorithm sorts the results by relevance.","AI"],
  ["data","ข้อมูล","AI needs a lot of data to learn.","AI"],
  ["dataset","ชุดข้อมูล","The dataset contains a million images.","AI"],
  ["model","แบบจำลอง / โมเดล","The model was trained on text from the web.","AI"],
  ["training","การฝึกโมเดล","Training the model took several weeks.","AI"],
  ["prompt","คำสั่งที่ป้อนให้ AI","A clear prompt gives a better answer.","AI"],
  ["chatbot","แชตบอต","The chatbot answers customer questions.","AI"],
  ["generative AI","เอไอสร้างสรรค์เนื้อหา","Generative AI can write text and draw images.","AI"],
  ["language model","แบบจำลองภาษา","A language model predicts the next word.","AI"],
  ["token","โทเคน (หน่วยข้อความ)","One token is roughly four characters.","AI"],
  ["parameter","พารามิเตอร์","The model has billions of parameters.","AI"],
  ["inference","การอนุมาน (การใช้โมเดลตอบ)","Inference is when the model produces an answer.","AI"],
  ["bias","อคติ","The system showed bias against some groups.","AI"],
  ["hallucination","การมโนข้อมูลผิด (AI)","The chatbot's hallucination gave a false fact.","AI"],
  ["accuracy","ความแม่นยำ","The accuracy of the model is 95 percent.","AI"],
  ["automation","ระบบอัตโนมัติ","Automation saves time on repetitive tasks.","AI"],
  ["robot","หุ่นยนต์","The robot assembles cars in the factory.","AI"],
  ["computer vision","คอมพิวเตอร์วิทัศน์","Computer vision lets machines recognize faces.","AI"],
  ["speech recognition","การรู้จำเสียงพูด","Speech recognition turns voice into text.","AI"],
  ["natural language processing","การประมวลผลภาษาธรรมชาติ","Natural language processing helps computers read text.","AI"],
  ["recommendation","ระบบแนะนำ / ข้อเสนอแนะ","The app gives a movie recommendation.","AI"],
  ["prediction","การทำนาย","The prediction was correct.","AI"],
  ["classify","จำแนกประเภท","The model classifies emails as spam or not.","AI"],
  ["optimize","ปรับให้มีประสิทธิภาพสูงสุด","We optimize the model for speed.","AI"],
  ["privacy","ความเป็นส่วนตัว","AI raises questions about privacy.","AI"],
  ["ethics","จริยธรรม","The ethics of AI are widely debated.","AI"],
  ["regulation","กฎระเบียบ","New regulation controls how AI is used.","AI"],
  ["artificial general intelligence","ปัญญาประดิษฐ์ทั่วไป (AGI)","AGI would match human ability in every task.","AI"],
  ["fine-tune","ปรับแต่งโมเดลเพิ่มเติม","We fine-tuned the model on medical data.","AI"],
  ["agent","เอไอเอเจนต์ / ตัวแทน","An AI agent can complete tasks on its own.","AI"],
  ["assistant","ผู้ช่วย","My AI assistant drafts my emails.","AI"],
  ["be","เป็น / อยู่ / คือ","I am a student.","กริยาที่ใช้บ่อย"],
  ["have","มี / กิน","I have two brothers.","กริยาที่ใช้บ่อย"],
  ["do","ทำ","What do you do?","กริยาที่ใช้บ่อย"],
  ["say","พูด / บอกว่า","She said hello.","กริยาที่ใช้บ่อย"],
  ["go","ไป","We go to school by bus.","กริยาที่ใช้บ่อย"],
  ["get","ได้รับ / เป็น","I got a gift from my friend.","กริยาที่ใช้บ่อย"],
  ["make","ทำ / สร้าง","She makes coffee every morning.","กริยาที่ใช้บ่อย"],
  ["know","รู้ / รู้จัก","I know him well.","กริยาที่ใช้บ่อย"],
  ["think","คิด","I think it is a good idea.","กริยาที่ใช้บ่อย"],
  ["take","เอาไป / ใช้เวลา","It takes ten minutes.","กริยาที่ใช้บ่อย"],
  ["see","เห็น / พบ","I see a bird.","กริยาที่ใช้บ่อย"],
  ["come","มา","Please come here.","กริยาที่ใช้บ่อย"],
  ["want","ต้องการ","I want some water.","กริยาที่ใช้บ่อย"],
  ["look","มอง / ดู","Look at the sky.","กริยาที่ใช้บ่อย"],
  ["use","ใช้","May I use your pen?","กริยาที่ใช้บ่อย"],
  ["find","หา / พบ","I can't find my keys.","กริยาที่ใช้บ่อย"],
  ["give","ให้","He gave me a book.","กริยาที่ใช้บ่อย"],
  ["tell","บอก / เล่า","Tell me the truth.","กริยาที่ใช้บ่อย"],
  ["work","ทำงาน","She works in a hospital.","กริยาที่ใช้บ่อย"],
  ["call","โทรหา / เรียก","I'll call you tonight.","กริยาที่ใช้บ่อย"],
  ["try","พยายาม / ลอง","Try this soup.","กริยาที่ใช้บ่อย"],
  ["ask","ถาม / ขอ","Can I ask a question?","กริยาที่ใช้บ่อย"],
  ["need","จำเป็นต้อง","We need more time.","กริยาที่ใช้บ่อย"],
  ["feel","รู้สึก","I feel tired today.","กริยาที่ใช้บ่อย"],
  ["become","กลายเป็น","He became a doctor.","กริยาที่ใช้บ่อย"],
  ["leave","ออกจาก / ทิ้งไว้","I leave home at seven.","กริยาที่ใช้บ่อย"],
  ["put","วาง","Put the book on the table.","กริยาที่ใช้บ่อย"],
  ["mean","หมายความว่า","What does this word mean?","กริยาที่ใช้บ่อย"],
  ["keep","เก็บไว้ / ทำต่อ","Keep the change.","กริยาที่ใช้บ่อย"],
  ["let","ปล่อย / ให้ (ทำ)","Let me help you.","กริยาที่ใช้บ่อย"],
  ["begin","เริ่ม","The class begins at nine.","กริยาที่ใช้บ่อย"],
  ["start","เริ่มต้น","Let's start the lesson.","กริยาที่ใช้บ่อย"],
  ["show","แสดง / ให้ดู","Show me your passport.","กริยาที่ใช้บ่อย"],
  ["hear","ได้ยิน","I can't hear you.","กริยาที่ใช้บ่อย"],
  ["play","เล่น","The kids play in the park.","กริยาที่ใช้บ่อย"],
  ["run","วิ่ง / ดำเนินการ","He runs every morning.","กริยาที่ใช้บ่อย"],
  ["move","เคลื่อนที่ / ย้าย","They moved to a new city.","กริยาที่ใช้บ่อย"],
  ["live","อาศัยอยู่","I live in Bangkok.","กริยาที่ใช้บ่อย"],
  ["believe","เชื่อ","I believe you.","กริยาที่ใช้บ่อย"],
  ["bring","นำมา","Please bring your laptop.","กริยาที่ใช้บ่อย"],
  ["write","เขียน","Write your name here.","กริยาที่ใช้บ่อย"],
  ["sit","นั่ง","Please sit down.","กริยาที่ใช้บ่อย"],
  ["stand","ยืน","Stand up, please.","กริยาที่ใช้บ่อย"],
  ["read","อ่าน","I read the news every day.","กริยาที่ใช้บ่อย"],
  ["eat","กิน","We eat dinner at six.","กริยาที่ใช้บ่อย"],
  ["drink","ดื่ม","Drink more water.","กริยาที่ใช้บ่อย"],
  ["sleep","นอนหลับ","I sleep eight hours a night.","กริยาที่ใช้บ่อย"],
  ["walk","เดิน","I walk to work.","กริยาที่ใช้บ่อย"],
  ["talk","พูดคุย","We talked for an hour.","กริยาที่ใช้บ่อย"],
  ["open","เปิด","Open the window, please.","กริยาที่ใช้บ่อย"],
  ["close","ปิด","Close the door.","กริยาที่ใช้บ่อย"],
  ["buy","ซื้อ","I want to buy a new phone.","กริยาที่ใช้บ่อย"],
  ["sell","ขาย","They sell fresh fruit.","กริยาที่ใช้บ่อย"],
  ["pay","จ่ายเงิน","I'll pay by card.","กริยาที่ใช้บ่อย"],
  ["help","ช่วยเหลือ","Can you help me?","กริยาที่ใช้บ่อย"],
  ["wait","รอ","Wait here for a moment.","กริยาที่ใช้บ่อย"],
  ["meet","พบ / ประชุม","Nice to meet you.","กริยาที่ใช้บ่อย"],
  ["send","ส่ง","Send me an email.","กริยาที่ใช้บ่อย"],
  ["choose","เลือก","Choose one answer.","กริยาที่ใช้บ่อย"],
  ["change","เปลี่ยน","Nothing will change.","กริยาที่ใช้บ่อย"],
  ["follow","ตาม","Follow me, please.","กริยาที่ใช้บ่อย"],
  ["remember","จำได้ / นึกออก","I remember his name.","กริยาที่ใช้บ่อย"],
  ["forget","ลืม","Don't forget your umbrella.","กริยาที่ใช้บ่อย"],
  ["love","รัก","I love my family.","กริยาที่ใช้บ่อย"],
  ["like","ชอบ","I like Thai food.","กริยาที่ใช้บ่อย"],
  ["stop","หยุด","Stop the car here.","กริยาที่ใช้บ่อย"],
  ["build","สร้าง / ก่อสร้าง","They build houses.","กริยาที่ใช้บ่อย"],
  ["teach","สอน","She teaches English.","กริยาที่ใช้บ่อย"],
  ["cook","ทำอาหาร","He cooks dinner for us.","กริยาที่ใช้บ่อย"]
];
