// [อังกฤษ, ไทย, ตัวอย่างประโยค, หมวด]
const WORDS = [
  ["hello","สวัสดี","Hello, how are you?","ทักทาย"],
  ["goodbye","ลาก่อน","Goodbye, see you tomorrow.","ทักทาย"],
  ["thank you","ขอบคุณ","Thank you for your help.","ทักทาย"],
  ["please","กรุณา / ได้โปรด","Please sit down.","ทักทาย"],
  ["sorry","ขอโทษ","I'm sorry I'm late.","ทักทาย"],
  ["welcome","ยินดีต้อนรับ","Welcome to Thailand.","ทักทาย"],
  ["apple","แอปเปิล","I eat an apple every day.","อาหาร"],
  ["banana","กล้วย","Monkeys love bananas.","อาหาร"],
  ["rice","ข้าว","We eat rice for lunch.","อาหาร"],
  ["water","น้ำ","Can I have some water?","อาหาร"],
  ["bread","ขนมปัง","She bought fresh bread.","อาหาร"],
  ["chicken","ไก่","Fried chicken is delicious.","อาหาร"],
  ["egg","ไข่","I had two eggs for breakfast.","อาหาร"],
  ["milk","นม","He drinks milk every morning.","อาหาร"],
  ["dog","สุนัข","The dog is barking.","สัตว์"],
  ["cat","แมว","The cat sleeps on the sofa.","สัตว์"],
  ["bird","นก","A bird is singing.","สัตว์"],
  ["fish","ปลา","There are fish in the pond.","สัตว์"],
  ["elephant","ช้าง","The elephant is the symbol of Thailand.","สัตว์"],
  ["horse","ม้า","She rides a horse.","สัตว์"],
  ["red","สีแดง","The rose is red.","สี"],
  ["blue","สีน้ำเงิน / สีฟ้า","The sky is blue.","สี"],
  ["green","สีเขียว","The grass is green.","สี"],
  ["yellow","สีเหลือง","The sun is yellow.","สี"],
  ["black","สีดำ","He wears a black hat.","สี"],
  ["white","สีขาว","Snow is white.","สี"],
  ["one","หนึ่ง","I have one brother.","ตัวเลข"],
  ["two","สอง","Two plus two is four.","ตัวเลข"],
  ["three","สาม","There are three books.","ตัวเลข"],
  ["ten","สิบ","Count to ten.","ตัวเลข"],
  ["hundred","ร้อย","A hundred people came.","ตัวเลข"],
  ["family","ครอบครัว","I love my family.","ครอบครัว"],
  ["mother","แม่","My mother is a teacher.","ครอบครัว"],
  ["father","พ่อ","My father works at a bank.","ครอบครัว"],
  ["brother","พี่ชาย / น้องชาย","My brother plays football.","ครอบครัว"],
  ["sister","พี่สาว / น้องสาว","My sister likes music.","ครอบครัว"],
  ["friend","เพื่อน","She is my best friend.","ครอบครัว"],
  ["school","โรงเรียน","The children go to school.","ทั่วไป"],
  ["book","หนังสือ","This book is interesting.","ทั่วไป"],
  ["house","บ้าน","They built a new house.","ทั่วไป"],
  ["car","รถยนต์","He drives a red car.","ทั่วไป"],
  ["time","เวลา","What time is it?","ทั่วไป"],
  ["happy","มีความสุข","I am happy today.","ทั่วไป"],
  ["beautiful","สวยงาม","What a beautiful view!","ทั่วไป"],
  ["difficult","ยาก","This question is difficult.","ทั่วไป"],
  ["learn","เรียนรู้","I want to learn English.","ทั่วไป"],
  ["understand","เข้าใจ","Do you understand me?","ทั่วไป"],
  ["travel","เดินทาง","They love to travel.","ทั่วไป"],
  ["airport","สนามบิน","We arrived at the airport.","เดินทาง"],
  ["hotel","โรงแรม","The hotel is near the beach.","เดินทาง"],
  ["ticket","ตั๋ว","I need to buy a ticket.","เดินทาง"],
  ["where","ที่ไหน","Where is the toilet?","เดินทาง"],
  ["how much","เท่าไหร่","How much is this?","เดินทาง"]
,
  ["agenda","วาระการประชุม","Please review the agenda before the meeting.","TOEIC"],
  ["attend","เข้าร่วม","All employees must attend the training.","TOEIC"],
  ["schedule","กำหนดการ / จัดตารางเวลา","Let's schedule a meeting for Monday.","TOEIC"],
  ["deadline","กำหนดส่ง","The deadline for the report is Friday.","TOEIC"],
  ["postpone","เลื่อนออกไป","The launch was postponed until May.","TOEIC"],
  ["cancel","ยกเลิก","They had to cancel the conference.","TOEIC"],
  ["colleague","เพื่อนร่วมงาน","I discussed the plan with a colleague.","TOEIC"],
  ["supervisor","หัวหน้างาน","Please report to your supervisor.","TOEIC"],
  ["employer","นายจ้าง","The employer offers health insurance.","TOEIC"],
  ["employee","พนักงาน","Each employee received a bonus.","TOEIC"],
  ["candidate","ผู้สมัคร","The candidate has five years of experience.","TOEIC"],
  ["resume","ประวัติย่อ (เรซูเม่)","Please attach your resume to the application.","TOEIC"],
  ["apply for","สมัคร (งาน)","She applied for a position in marketing.","TOEIC"],
  ["qualification","คุณสมบัติ / วุฒิ","He has the right qualifications for the job.","TOEIC"],
  ["promote","เลื่อนตำแหน่ง / ส่งเสริม","She was promoted to manager.","TOEIC"],
  ["resign","ลาออก","He resigned to start his own company.","TOEIC"],
  ["retire","เกษียณ","My father will retire next year.","TOEIC"],
  ["salary","เงินเดือน","The salary is paid monthly.","TOEIC"],
  ["benefit","สวัสดิการ / ประโยชน์","The company offers excellent benefits.","TOEIC"],
  ["invoice","ใบแจ้งหนี้","Please send the invoice by email.","TOEIC"],
  ["receipt","ใบเสร็จ","Keep the receipt for your records.","TOEIC"],
  ["refund","คืนเงิน","You can get a full refund within 30 days.","TOEIC"],
  ["budget","งบประมาณ","We need to reduce our budget.","TOEIC"],
  ["revenue","รายได้","Annual revenue increased by 10 percent.","TOEIC"],
  ["profit","กำไร","The firm made a large profit this year.","TOEIC"],
  ["expense","ค่าใช้จ่าย","Travel expenses will be reimbursed.","TOEIC"],
  ["estimate","ประเมินราคา / การประเมิน","Can you give me an estimate?","TOEIC"],
  ["payment","การชำระเงิน","Payment is due within 14 days.","TOEIC"],
  ["purchase","ซื้อ / การซื้อ","She made a purchase online.","TOEIC"],
  ["order","สั่งซื้อ / คำสั่งซื้อ","We placed an order for new laptops.","TOEIC"],
  ["shipment","การขนส่งสินค้า","The shipment will arrive on Tuesday.","TOEIC"],
  ["deliver","จัดส่ง","We deliver within three business days.","TOEIC"],
  ["inventory","สินค้าคงคลัง","We check our inventory every week.","TOEIC"],
  ["supplier","ผู้จัดหาสินค้า","The supplier raised its prices.","TOEIC"],
  ["customer","ลูกค้า","The customer is always right.","TOEIC"],
  ["client","ลูกค้า (ผู้ใช้บริการ)","We are meeting a new client today.","TOEIC"],
  ["contract","สัญญา","Both parties signed the contract.","TOEIC"],
  ["negotiate","เจรจาต่อรอง","They negotiated a better price.","TOEIC"],
  ["proposal","ข้อเสนอ","The board approved the proposal.","TOEIC"],
  ["approve","อนุมัติ","The manager approved my vacation request.","TOEIC"],
  ["require","ต้องการ / กำหนดให้","This job requires good communication skills.","TOEIC"],
  ["submit","ส่ง (เอกสาร)","Submit your application by noon.","TOEIC"],
  ["review","ตรวจทาน / รีวิว","Please review the document carefully.","TOEIC"],
  ["revise","แก้ไขปรับปรุง","We revised the schedule.","TOEIC"],
  ["confirm","ยืนยัน","I'd like to confirm my reservation.","TOEIC"],
  ["reserve","จอง","I reserved a table for four.","TOEIC"],
  ["available","ว่าง / มีให้","Is the manager available now?","TOEIC"],
  ["board","คณะกรรมการ / ขึ้น (เครื่องบิน)","The board of directors will meet today.","TOEIC"],
  ["headquarters","สำนักงานใหญ่","Our headquarters is in Bangkok.","TOEIC"],
  ["branch","สาขา","They opened a new branch downtown.","TOEIC"],
  ["department","แผนก","She works in the sales department.","TOEIC"],
  ["facility","สิ่งอำนวยความสะดวก","The hotel has excellent facilities.","TOEIC"],
  ["equipment","อุปกรณ์","The office equipment is old.","TOEIC"],
  ["maintenance","การบำรุงรักษา","The elevator is under maintenance.","TOEIC"],
  ["install","ติดตั้ง","A technician will install the software.","TOEIC"],
  ["replace","เปลี่ยนแทน","Please replace the broken printer.","TOEIC"],
  ["recommend","แนะนำ","I recommend this restaurant.","TOEIC"],
  ["in advance","ล่วงหน้า","Please book tickets in advance.","TOEIC"],
  ["as soon as possible","โดยเร็วที่สุด","Please reply as soon as possible.","TOEIC"],
  ["be responsible for","รับผิดชอบ","She is responsible for the project.","TOEIC"],
  ["be located in","ตั้งอยู่ที่","The office is located in Silom.","TOEIC"],
  ["according to","ตามที่ / อ้างอิงจาก","According to the report, sales are up.","TOEIC"],
  ["regarding","เกี่ยวกับ","I'm writing regarding your order.","TOEIC"],
  ["in charge of","รับผิดชอบดูแล","He is in charge of hiring.","TOEIC"],
  ["boarding pass","บัตรขึ้นเครื่อง","Show your boarding pass at the gate.","TOEIC"],
  ["itinerary","กำหนดการเดินทาง","Here is your travel itinerary.","TOEIC"],
  ["delay","ล่าช้า","The flight was delayed by two hours.","TOEIC"],
  ["luggage","สัมภาระ / กระเป๋าเดินทาง","Your luggage is at carousel 3.","TOEIC"]
];
